fix: init skip chance trend for all years
Avoid the error in the tests below at each change of year
```
>       is_skipped = random.random() < self.skip_chance_trend[year_index]                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E       IndexError: index 6 is out of bounds for axis 0 with size 6

FAILED tests/factories/test_spotify.py::test_create_streaming_history[6] - IndexError: index 6 is out of bounds for axis 0 with size 6
```